flask:
  replicaCount: 1
  image:
    repository: danielkolodko/cat-gifs-app
    tag: "latest"
  serviceType: LoadBalancer

  # Environment variables stored in the configMap
  app: "app.py"
  env: "production"

  # Example SQLAlchemy URI
  databaseUri: "mysql+pymysql://catuser:catpassword@catshelm-helmchart-mysql-service/catgifs"

mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: "8.0"
  rootPassword: "eroot"
  user: "catuser"
  password: "catpassword"
  database: "catgifs"
  storageSize: "5Gi"

seedJob:
  enabled: true
  image:
    repository: mysql
    tag: "8.0"
  database:
    host: "catshelm-helmchart-mysql-service"
    user: "catuser"
    password: "catpassword"
    name: "catgifs"

  # Name of the ConfigMap holding your dump.sql
  configMapName: "db-dump-config"
