version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eroot
      MYSQL_DATABASE: catgifs
      MYSQL_USER: catuser
      MYSQL_PASSWORD: catpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      # This connection string tells SQLAlchemy to use PyMySQL to connect
      # to the MySQL container named "db" with the provided credentials.
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://catuser:catpassword@db/catgifs"
    depends_on:
      - db

volumes:
  db_data:
