apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup-cronjob
spec:
  schedule: "0 3 * * *"  # daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: google/cloud-sdk:latest
            env:
              - name: MYSQL_HOST
                value: mysql-service
              - name: MYSQL_USER
                value: catuser
              - name: MYSQL_PASSWORD
                value: catpassword
              - name: MYSQL_DATABASE
                value: catgifs
              - name: BUCKET_NAME
                value: my-sql-db-backup-bucket
            command:
              - /bin/sh
              - -c
              - |
                DATE=$(date +"%Y-%m-%d-%H-%M")
                mysqldump -h$MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /tmp/db-backup-$DATE.sql
                gsutil cp /tmp/db-backup-$DATE.sql gs://$BUCKET_NAME/db-backup-$DATE.sql
        containers:
        - name: db-backup
          image: google/cloud-sdk:latest
          command:
          - /bin/bash
          - -c
          - |
            DATE=$(date +%Y%m%d%H%M%S)
            mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /tmp/db-backup-$DATE.sql
            gsutil cp /tmp/db-backup-$DATE.sql gs://$BUCKET_NAME/
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
        restartPolicy: OnFailure
