apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: danielkolodko/workingcats:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: FLASK_APP
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: FLASK_ENV
        - name: SQLALCHEMY_DATABASE_URI
          value: "mysql+pymysql://catuser:catpass@mysql-service/catgifs"
      imagePullSecrets:
      - name: regcred
