apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmchart.fullname" . }}-flask-deployment
  labels:
    app: {{ include "helmchart.name" . }}-flask
spec:
  replicas: {{ .Values.flask.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helmchart.name" . }}-flask
  template:
    metadata:
      labels:
        app: {{ include "helmchart.name" . }}-flask
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag }}"
          ports:
            - name: metrics
              containerPort: 5000
          env:
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helmchart.fullname" . }}-flask-config
                  key: FLASK_APP
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helmchart.fullname" . }}-flask-config
                  key: FLASK_ENV
            - name: SQLALCHEMY_DATABASE_URI
              value: {{ .Values.flask.databaseUri | quote }}
      # Uncomment the imagePullSecrets block if you need to pull from a private registry
      # imagePullSecrets:
      #   - name: regcred

