apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-flask-service
  labels:
    app: {{ include "helmchart.name" . }}-flask
spec:
  selector:
    app: {{ include "helmchart.name" . }}-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: metrics
  type: {{ .Values.flask.serviceType }}
