apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-flask-service
spec:
  selector:
    app: {{ include "helmchart.name" . }}-flask
  ports:
    - protocol: TCP
      port: {{ .Values.service.flask.port }}
      targetPort: {{ .Values.service.flask.targetPort }}
  type: {{ .Values.service.flask.type }}
