apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-mysql-service
  labels:
    app: {{ include "helmchart.name" . }}-mysql
spec:
  selector:
    app: {{ include "helmchart.name" . }}-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
