apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmchart.fullname" . }}-mysql-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helmchart.name" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ include "helmchart.name" . }}-mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.image.mysql.repository }}:{{ .Values.image.mysql.tag }}"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "helmchart.fullname" . }}-mysql-secret
                key: mysql-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ include "helmchart.fullname" . }}-mysql-secret
                key: mysql-database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "helmchart.fullname" . }}-mysql-secret
                key: mysql-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "helmchart.fullname" . }}-mysql-secret
                key: mysql-password
        ports:
          - containerPort: {{ .Values.service.mysql.targetPort }}
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ include "helmchart.fullname" . }}-mysql-pvc
