apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-mysql-service
spec:
  selector:
    app: {{ include "helmchart.name" . }}-mysql
  ports:
    - protocol: TCP
      port: {{ .Values.service.mysql.port }}
      targetPort: {{ .Values.service.mysql.targetPort }}
  type: ClusterIP
