apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helmchart.fullname" . }}-mysql-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
