apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helmchart.fullname" . }}-mysql-pvc
  labels:
    app: {{ include "helmchart.name" . }}-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storageSize }}
