{{- if .Values.seedJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helmchart.fullname" . }}-seed-db-job
  labels:
    app: {{ include "helmchart.name" . }}-seed-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: "{{ .Values.seedJob.image.repository }}:{{ .Values.seedJob.image.tag }}"
          command: ["sh", "-c", "mysql -h {{ .Values.seedJob.database.host }} -u {{ .Values.seedJob.database.user }} -p{{ .Values.seedJob.database.password }} {{ .Values.seedJob.database.name }} < /dump/dump.sql"]
          volumeMounts:
            - name: dump-volume
              mountPath: /dump
      volumes:
        - name: dump-volume
          configMap:
            name: {{ .Values.seedJob.configMapName }}
{{- end }}
