name: CD

on:
  push:
    tags:
      - 'v*'      # Trigger when pushing tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Authenticate to Google Cloud using the service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 3. Set up Cloud SDK (do not pass service_account_key here)
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 4. Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      # 5. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform init

      # 6. Terraform Import Bucket (import the existing bucket into state)
      - name: Terraform Import Bucket
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: onyx-seeker-451213-q9
        run: |
          terraform import google_storage_bucket.sql_backup_bucket my-sql-db-backup-bucket || echo "Bucket already imported"

      # 7. Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: terraform plan

      # 8. Terraform Import Cluster (import existing cluster into state)
      - name: Terraform Import Cluster
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: |
          terraform import google_container_cluster.primary projects/onyx-seeker-451213-q9/locations/us-central1/clusters/cat-gifs-cluster || echo "Cluster already imported"

      # 9. Terraform Import Node Pool (import existing node pool into state)
      - name: Terraform Import Node Pool
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: |
          terraform import google_container_node_pool.primary_nodes projects/onyx-seeker-451213-q9/locations/us-central1/clusters/cat-gifs-cluster/nodePools/cat-gifs-node-pool || echo "Node pool already imported"

      # 10. Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: terraform apply -auto-approve

      # 11. Install gke-gcloud-auth-plugin so kubectl can use it
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      # 12. Configure GKE credentials (generate kubeconfig dynamically)
      - name: Configure GKE credentials
        run: |
          gcloud container clusters get-credentials cat-gifs-cluster --region us-central1 --project onyx-seeker-451213-q9

      # 13. Deploy Grafana & Prometheus via Helm (kube-prometheus-stack)
      - name: Deploy Grafana & Prometheus via Helm
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --wait \
            --history-max=1 \
            --force \

      # 14. Deploy your application to Kubernetes using Helm
      - name: Deploy Application via Helm
        run: |
          helm upgrade --install catshelm ./helmchart --namespace default --wait --history-max=1 --force
