name: Package and Push Helm Chart

on:
  push:
    tags:
      - 'v*'      # Trigger when pushing tags like v1.0.0
  workflow_dispatch:

jobs:
  package-chart:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 2. Package the Helm chart (this creates your .tgz chart package)
      - name: Package Helm Chart
        run: |
          helm package ./helmchart
          ls -l *.tgz

      # 3. Authenticate to Google Cloud using your service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 4. Set up Cloud SDK without service_account_key input
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 5. Upload the packaged chart(s) and update the repository index
      - name: Upload Chart Package and Update Index
        run: |
          # Upload all chart packages (e.g., helmchart-0.1.0.tgz, helmchart-0.2.0.tgz, etc.)
          gsutil cp *.tgz gs://helm-charts1306/
          # Create or update the Helm repository index using the bucket's public URL
          helm repo index . --url https://storage.googleapis.com/helm-charts1306
          ls -l index.yaml
          # Upload the updated index file
          gsutil cp index.yaml gs://helm-charts1306/
