name: Package and Push Helm Chart

on:
  push:
    tags:
      - 'v*'      # Trigger when pushing tags like v1.0.0
  workflow_dispatch:

jobs:
  package-chart:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # 2. Package the Helm chart (this creates cats-0.1.0.tgz)
      - name: Package Helm Chart
        run: |
          helm package ./helmchart
          ls -l *.tgz

      # 3. Set up Google Cloud SDK for authentication
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 4. Upload the packaged chart to the GCS bucket and update the index
      - name: Upload Chart Package and Update Index
        run: |
          # Replace "helmchart-0.1.0.tgz" with your actual chart package name if different.
          gsutil cp helmchart-0.1.0.tgz gs://helm-charts1306/
          # Create or update the index file in the current directory.
          helm repo index . --url https://storage.googleapis.com/helm-charts1306
          ls -l index.yaml
          # Upload the updated index file.
          gsutil cp index.yaml gs://helm-charts1306/
