name: Package and Push Helm Chart

on:
  push:
    tags:
      - 'v*'      # Trigger when pushing tags like v1.0.0
  workflow_dispatch:

jobs:
  package-chart:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the cats repository (your main project)
      - name: Checkout Cats Repository
        uses: actions/checkout@v2

      # 2. Build or update your Helm chart package from the cats repo.
      #    Assume your chart is in the "helm" directory of this repo.
      - name: Package Helm Chart
        run: |
          cd helm
          # Extract version from tag, update Chart.yaml accordingly (optional)
          TAG_VERSION=${GITHUB_REF##*/}
          CHART_VERSION=${TAG_VERSION#v}
          echo "Using chart version: ${CHART_VERSION}"
          sed -i "s/^version:.*/version: \"${CHART_VERSION}\"/" Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${CHART_VERSION}\"/" Chart.yaml
          cd ..
          # Package the chart (resulting package will be at the repository root)
          helm package helm

      # 3. Checkout the separate Helm repo (hosting your charts on GitHub Pages)
      - name: Checkout Helm Repo
        uses: actions/checkout@v2
        with:
          repository: DanielKolodko/helm  # Replace with your Helm repository name
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          path: helm-repo

      # 4. Copy the new chart package into the Helm repo directory
      - name: Copy Chart Package to Helm Repo
        run: |
          # Assumes the new package is named "cats-<version>.tgz" (or adjust accordingly)
          cp *.tgz helm-repo/

      # 5. Update the Helm repository index
      - name: Update Helm Repository Index
        working-directory: helm-repo
        run: |
          helm repo index . --url https://danielkolodko.github.io/helm

      # 6. Commit and push the updated Helm repo
      - name: Commit and Push Helm Repo
        working-directory: helm-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Helm chart to version ${CHART_VERSION}" || echo "No changes to commit"
          git push
