name: CI

on:
  push:
    branches: [ master ]
    tags: ['v*']   # Trigger on tag pushes like v1.0.0
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests (if defined)
      - name: Run tests
        run: |
          echo "Running tests... (no tests defined)"

      # 5. Build Docker image using your Docker Hub namespace
      - name: Build Docker image
        run: |
          docker build --no-cache -t danielkolodko/cat-gifs-app:latest .

      # 6. Determine image tag (version) and tag the image
      - name: Tag Docker Image
        id: docker_tags
        run: |
          # If triggered by a tag event, use that tag (strip the 'refs/tags/' prefix)
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              IMAGE_TAG=${GITHUB_REF#refs/tags/}
          else
              IMAGE_TAG=$(git rev-parse --short HEAD)
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "Tagging image as: ${IMAGE_TAG}"
          docker tag danielkolodko/cat-gifs-app:latest danielkolodko/cat-gifs-app:${IMAGE_TAG}

      # 7. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 8. Push Docker images
      - name: Push Docker Images
        run: |
          docker push danielkolodko/cat-gifs-app:latest
          docker push danielkolodko/cat-gifs-app:${{ env.IMAGE_TAG }}
