name: CD

on:
  push:
    tags:
      - 'v*'      # Trigger when pushing tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up GCP credentials using the service account key
      - name: Set up GCP credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: onyx-seeker-451213-q9
          export_default_credentials: true

      # 3. Activate the service account
      - name: Activate service account
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > ${HOME}/gcloud-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
          gcloud auth list

      # 4. Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      # 5. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: terraform init

      # 6. Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: onyx-seeker-451213-q9
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: terraform plan

      # 7. Terraform Import Cluster (import existing cluster into state)
      - name: Terraform Import Cluster
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: onyx-seeker-451213-q9
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: |
          terraform import google_container_cluster.primary projects/onyx-seeker-451213-q9/locations/us-central1/clusters/cat-gifs-cluster || echo "Cluster already imported"
      
      # 7.1. Terraform Import Node Pool (import existing node pool into state)
      - name: Terraform Import Node Pool
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: onyx-seeker-451213-q9
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: |
          terraform import google_container_node_pool.primary_nodes projects/onyx-seeker-451213-q9/locations/us-central1/clusters/cat-gifs-cluster/nodePools/cat-gifs-node-pool || echo "Node pool already imported"

      # 8. Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          TF_VAR_project: onyx-seeker-451213-q9
          TF_VAR_region: us-central1
          TF_VAR_machine_type: e2-medium
          TF_VAR_disk_size_gb: 100
          TF_VAR_disk_type: pd-standard
        run: terraform apply -auto-approve

      # 9. Build the Docker image for your app
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cat-gifs-app:latest .

      # 10. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 11. Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cat-gifs-app:latest

      # 12. Install gke-gcloud-auth-plugin so kubectl can use it
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      # 13. Configure GKE credentials (generate kubeconfig dynamically)
      - name: Configure GKE credentials
        run: |
          gcloud container clusters get-credentials cat-gifs-cluster --region us-central1 --project onyx-seeker-451213-q9

      # 14. Create Docker Registry Secret for image pulling
      - name: Create Docker Registry Secret
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server="${{ secrets.DOCKER_SERVER }}" \
            --docker-username="${{ secrets.DOCKER_USERNAME }}" \
            --docker-password="${{ secrets.DOCKER_TOKEN }}" \
            --docker-email="${{ secrets.DOCKER_EMAIL }}" \
            --namespace=default || echo "Secret already exists"

      # 15. (Optional) Create ConfigMap for DB dump if using seed-job that relies on it
      - name: Create ConfigMap for DB Dump
        run: |
          kubectl create configmap db-dump-config --from-file=dump.sql --namespace=default || echo "ConfigMap already exists"

      # 16. Deploy your application to Kubernetes using your manifests or Helm
      - name: Deploy via Helm
        run: |
          # Add your remote Helm repository that hosts your chart
          helm repo add helmcatrepo https://danielkolodko.github.io/helm || helm repo update
          helm repo update
          export HELM_STORAGE_DRIVER=configmap
          helm upgrade --install my-release helmcatrepo/cat-gifs --namespace default --wait --history-max=1

      # 17. Seed the Database using the Seed Job
      - name: Seed Database
        run: |
          kubectl apply -f k8s/seed-job.yaml
          kubectl wait --for=condition=complete --timeout=120s job/seed-db-job || kubectl logs job/seed-db-job
