name: 'Terraform GCP Destroy Pipeline'

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: 'Terraform Destroy GCP Infrastructure'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Check for GCP Service Account Key
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "Error: GCP_SA_KEY secret is not available. Please ensure it's set in repository secrets."
            exit 1
          fi

      - name: Setup Google Cloud credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
